src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`user`")
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cet email est déjà utilisé par un autre utilisateur !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmez le mot de passe")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\OneToMany(targetEntity=Registration::class, mappedBy="user", orphanRemoval=true)
     */
    private $registrations;

    /**
     * @ORM\ManyToMany(targetEntity=Matter::class, inversedBy="users")
     */
    private $matters;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="author", orphanRemoval=true)
     */
    private $answers;

    /**
     * @ORM\OneToMany(targetEntity=Claim::class, mappedBy="author", orphanRemoval=true)
     */
    private $claims;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $blocked;

    /**
     * @ORM\PrePersist
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->blocked)) {
            $this->blocked = 0;
        }
    }

    public function __toString(): string
    {
        return $this->lastName . ' ' . $this->firstName . ' (' . $this->email . ')';
    }

    public function getFullName()
    {
        return "{$this->lastName} {$this->firstName}";
    }

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
        $this->matters = new ArrayCollection();
        $this->claims = new ArrayCollection();
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /* Avatar path*/
    public function getAvatarPath()
    {
        return '/uploads/avatars/' . $this->getAvatar();
    }

    /**
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setUser($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getUser() === $this) {
                $registration->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Matter[]
     */
    public function getMatters(): Collection
    {
        return $this->matters;
    }

    public function addMatter(Matter $matter): self
    {
        if (!$this->matters->contains($matter)) {
            $this->matters[] = $matter;
        }

        return $this;
    }

    public function removeMatter(Matter $matter): self
    {
        $this->matters->removeElement($matter);

        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setAuthor($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getAuthor() === $this) {
                $answer->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Claim[]
     */
    public function getClaims(): Collection
    {
        return $this->claims;
    }

    public function addClaim(Claim $claim): self
    {
        if (!$this->claims->contains($claim)) {
            $this->claims[] = $claim;
            $claim->setAuthor($this);
        }

        return $this;
    }

    public function removeClaim(Claim $claim): self
    {
        if ($this->claims->removeElement($claim)) {
            // set the owning side to null (unless already changed)
            if ($claim->getAuthor() === $this) {
                $claim->setAuthor(null);
            }
        }

        return $this;
    }


    /**
     * Get the value of profile
     */ 
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Set the value of profile
     *
     * @return  self
     */ 
    public function setProfile($profile)
    {
        $this->profile = $profile;

        return $this;
    }

    public function getBlocked(): ?bool
    {
        return $this->blocked;
    }

    public function setBlocked(?bool $blocked): self
    {
        $this->blocked = $blocked;

        return $this;
    }
}

templates/base/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <link rel="icon" type="image/x-icon" href="{{asset('assets/medias/images/uvci.ico')}}"/>

        <title>UVCI e-Reclamations | {% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="{{asset('assets/ui/css/bootstrap.min.css')}}">
        <link rel="stylesheet" href="{{asset('assets/ui/css/fontawesome/all.css')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{{asset('assets/ui/css/styles.css')}}">
        <link rel="stylesheet" href="{{asset('assets/ui/css/app.css')}}">
        {# --DateTables-- #}
        <link rel="stylesheet" href="{{asset('assets/datatables/datatables.min.css')}}">
        <link rel="stylesheet" href="{{asset('assets/datatables/pack/css/dataTables.bootstrap4.min.css')}}">
        <link rel="stylesheet" href="{{asset('assets/datatables/pack/css/dataTables.jqueryui.min.css')}}">
        <link rel="stylesheet" href="{{asset('assets/datatables/pack/css/jquery.dataTables.min.css')}}">
        {# -- -- #}
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    
        {% include "base/header.html.twig" %}

        {#{% for label, messages in app.flashes %}
            <div class="container">
                <div class="alert alert-{{ label }}">
                    {% for message in messages %}
                        <p>{{ message | raw }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}#}

        {# toast #}
        {% for label, messages in app.flashes %}
                <div class="position-fixed bottom-0 right-0 p-3" style="z-index: 5; right: 0; bottom: 0;">
                    <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-delay="3000">
                        <div class="toast-header text-white" style="background-color:#800080;">
                            <strong class="mr-auto">UVCI e-Reclamations</strong>
                            <button type="button" class="ml-2 mb-1 text-white close" data-dismiss="toast" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="toast-body text-white bg-{{ label }}">
                            {% for message in messages %}
                                <p>{{ message | raw }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}

        {% block body %}{% endblock %}

        {% include "base/footer.html.twig" %}

        <script src="{{asset('assets/ui/js/jquery-3.5.1.min.js')}}"></script>
        <script src="{{asset('assets/ui/js/popper.min.js')}}"></script>
        <script src="{{asset('assets/ui/js/bootstrap.min.js')}}"></script>
        <script src="{{asset('assets/ui/js/fontawesome/all.min.js')}}"></script>
        {# --DateTables-- #}
        <script src="{{asset('assets/datatables/datatables.min.js')}}"></script>
        <script src="{{asset('assets/datatables/pack/js/bootstrap.bundle.min.js')}}"></script>
        <script src="{{asset('assets/datatables/pack/js/dataTables.bootstrap4.min.js')}}"></script>
        <script src="{{asset('assets/datatables/pack/js/dataTables.jqueryui.min.js')}}"></script>
        <script src="{{asset('assets/datatables/pack/js/jquery.dataTables.min.js')}}"></script>
        <script src="{{asset('assets/datatables/call.dataTables.jquery.js')}}"></script>
        {# -- -- #}
        {# jQuery Modal => https://jquerymodal.com/ #}

        {% block javascripts %}{% endblock %}

        <script>
            $(document).ready(function(){
            $('.toast').toast('show');
            });
        </script>
    </body>
</html>

templates/base/footer.html.twig
<div class="container-fluid mt-auto">
    <div class="row justify-content-center">
        <div class="col-md-6 small">Copyright &#xA9; UVCI</div>
    </div>
</div>

templates/base/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#800080;">
    <a class="navbar-brand" href="{{ path('account') }}"><i class="fas fa-home fa-1x"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('admin') }}">
                        <i class="fas fa-tachometer-alt"></i>&nbsp;Tableau de bord
                    </a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-question-circle"></i>&nbsp;FAQ
                </a>
            </li>  
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                {#<a class="nav-link dropdown-toggle" href="#" id="accountDropdownLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                    {% if app.user.avatar is empty %}
                        <span class="ml-2 text-bold text-white">{{app.user.fullName|title}}</span>
                    {% else %}
                        <img src="{{app.user.avatarPath}}" class="avatar avatar-mini" alt="Avatar"><span class="ml-2 text-bold text-white">{{app.user.fullName|title}}</span>
                    {% endif %}                   
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                    <div class="dropdown-item">
                        <i class="fas fa-user"></i>&nbsp;{{ app.user.fullName }}
                    </div>
                    <div class="dropdown-divider"></div>
                    <a href="{{ path('update_user_account') }}" class="dropdown-item">
                        <i class="fas fa-edit"></i>&nbsp;Afficher votre profil
                    </a>
                    <a href="{{ path('account_password') }}" class="dropdown-item">
                        <i class="fas fa-key"></i>&nbsp;Modifier votre mot de passe
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ path('app_logout') }}" class="dropdown-item">
                        <i class="fas fa-sign-out-alt"></i>&nbsp;Déconnexion
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>